app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', ['uses'=>'HomeController@index', 'as' => 'home']);
Route::post('/switch', [function() {$t = $_POST['localei'];$currURl = trim($_POST['currURl']);Session::put('localei', $t);App::setLocale($t);return Redirect::route($currURl);}, 'as' => 'user.mylang']);
Route::get('about', ['uses'=>'HomeController@about', 'as' => 'user.about']);
Route::get('driver-list', ['uses'=>'HomeController@driverList', 'as' => 'user.driver-list']);
Route::get('trip-list', ['uses'=>'HomeController@tripSearch', 'as' => 'user.trip-list']);
Route::get('trip-list-map', ['uses'=>'HomeController@tripListmap', 'as' => 'user.trip-list-map']);
Route::get('item-list', ['uses'=>'HomeController@itemList', 'as' => 'user.item-list']);
Route::get('item-list-map', ['uses'=>'HomeController@itemListmap', 'as' => 'user.item-list-map']);

Route::get('item-view/{item_id}', ['uses'=>'HomeController@itemView', 'as' => 'user.item-view']);
Route::get('driver-detail/{driver_id}', ['uses'=>'HomeController@driverDetail', 'as' => 'user.driver-detail']);
Route::get('signin', ['uses'=>'HomeController@getlogin', 'as' => 'user.signin']);
Route::post('signin', ['uses'=>'HomeController@signin', 'as' => 'user.signin']);
Route::get('signup', ['uses'=>'HomeController@signup', 'as' => 'user.signup']);
Route::post('signup', ['uses'=>'HomeController@dosignup', 'as' => 'user.signup']);
Route::get('forgot-password', ['uses'=>'HomeController@forgotPassword', 'as' => 'user.forgotpassword']);
Route::post('forgot-password', ['uses'=>'HomeController@sentVerificationCode', 'as' => 'user.forgotpassword']);
Route::get('verification-code', ['uses'=>'HomeController@verificationCode', 'as' => 'user.verify_code']);
Route::post('verification-code', ['uses'=>'HomeController@checkVerifyCode', 'as' => 'user.verify_code']);
Route::get('change-password', ['uses'=>'HomeController@changePassword', 'as' => 'user.change.password']);
Route::post('change-password', ['uses'=>'HomeController@editPassword', 'as' => 'user.change.password']);
Route::get('logout', ['uses'=>'HomeController@logout', 'as' => 'user.logout']);
Route::get('disclaimer', ['uses'=>'HomeController@Disclaimer', 'as' => 'user.disclaimer']);
Route::get('terms-and-conditions', ['uses'=>'HomeController@TermsAndCondtions', 'as' => 'user.terms-and-conditions']);
Route::get('contact', ['uses'=>'HomeController@Contact', 'as' => 'user.contact']);
Route::post('contact', ['uses'=>'HomeController@AddContact', 'as' => 'user.contact']);


Route::group(['middleware' => 'check_role'], function() {    
    Route::get('dashboard', ['uses'=>'HomeController@dashboard', 'as' => 'user.dashboard']);
    Route::get('myprofile', ['uses'=>'UserController@myprofile', 'as' => 'user.profile']);
    Route::post('myprofile', ['uses'=>'UserController@updateprofile', 'as' => 'user.profile']);
    /*
     * Get Carmodel by car type id
     * Created Dt: 02-Nov-2016   
     */
    Route::get('driver-profile', ['uses'=>'UserController@showDriverProfile', 'as' => 'user.driver_profile']);
    Route::post('driver-profile', ['uses'=>'UserController@addProfileAsDriver', 'as' => 'user.driver_profile']);
    /*
     * Get Carmodel by car type id
     * Created Dt: 03-Nov-2016
     */
    Route::get('driver-registration', ['uses'=>'UserController@showDriverRegistration', 'as' => 'user.driver_registration']);
    Route::post('driver-registration', ['uses'=>'UserController@addDriverRegistration', 'as' => 'user.driver_registration']);
    /*
     * Get Carmodel by car type id
     * Created Dt: 03-Nov-2016   
     */
    Route::post('carmodel', ['uses'=>'UserController@carmodelByCarTypeID', 'as' => 'carmodel']);
    /*
     * Trip Model
     * Created Dt: 04-Nov-2016   
     */
     Route::resource('trip', 'TripController', ['except' => ['destroy','update']]);
    /*
     * Get trip information by Trip ID
     * Method : POST BY AJAX
     */
    Route::post('tripinfo', ['uses'=>'TripController@tripInfoByID', 'as'=>'tripinfo']);    
    Route::put('trip', ['uses'=>'TripController@update', 'as'=>'trip.update']);
    Route::post('trip-delete', ['uses'=>'TripController@destroy', 'as'=>'trip_destroy']);
    /*
     * Items Model
     * Created Dt: 05-Nov-2016   
     */
    Route::resource('item', 'ItemController', ['except' => ['destroy']]);
    Route::get('item-delete/{item_id}', ['uses'=>'ItemController@destroy', 'as'=>'item_destroy']);    
    Route::post('subcategorybycatid', ['uses'=>'MainController@subCategoryByCategoryID', 'as' => 'subcategory_by_categoryid']);
    Route::post('subcategorybysubcatid', ['uses'=>'MainController@subCategoryBySubCatID', 'as' => 'subcategory_by_subcatid']);
    Route::get('diling-code/{country_id}', ['uses'=>'HomeController@getCountryDilingCodeByCountryID', 'as' => 'diling_code']);
    /*
     * Notification by driver to user for item
     */
    Route::post('item-request-accept-buyer', ['uses'=>'ItemController@itemRequestAcceptByDriver', 'as'=>'item_request_accept_buyer']);
    Route::get('view-notification/{notifi_id}', ['uses'=>'ItemController@viewNotification', 'as'=>'view_notification']);
    Route::get('show-notification/{notifi_id}', ['uses'=>'ItemController@showNotification', 'as'=>'show_notification']);
    Route::post('make-another-itemoffer', ['uses'=>'ItemController@makeAnotherItemOffer', 'as' => 'make_another_itemoffer']);
    
    /*
     * Notification by buyer to driver for item
     */
    Route::post('buyer-request-driver', ['uses'=>'ItemController@buyerRequestDriverForItem', 'as' => 'buyer_request_driver']);
    /*
     * Deny deriver request
     * Created Dt: 24-Nov-2016     
     */
    Route::get('deny-driver-request/{request_id}', ['uses'=>'ItemController@denyDriverRequest', 'as' => 'deny_driver_request']);
    
    /*
     * 
     */
    Route::get('accept-driver-request/{request_id}', ['uses'=>'ItemController@acceptDriverRequest', 'as' => 'accept_driver_request']);
    
    /*
     * Controller : User
     * Function: contactDriver     
     * Created Date: 28-Nov-2016
     */
    Route::get('contact-driver/{driver_id}', ['uses'=>'UserController@contactDriver', 'as' => 'contact_driver']);
    
    /*
     * Controller : Item
     * Function: userItems by ajax     
     * Created Date: 29-Nov-2016
     */
    Route::post('user-items', ['uses'=>'ItemController@userItems', 'as' => 'user_items']);
    /*
     * Controller : Item
     * Function: userItems by ajax     
     * Created Date: 29-Nov-2016
     */
    Route::post('user-trips', ['uses'=>'TripController@userTrips', 'as' => 'user_trips']);
    Route::post('car-img-upload', ['uses'=>'UserController@carImgUpload', 'as'=>'car_img_upload']);
});
/*
 * Created Date: 28-Nov-2016
 * Created By: Rahul Gupta
 * Admin Section
 */
Route::group(["namespace" => 'Admin', "prefix" => "admin"], function() {    
    Route::get('/', ['uses'=>'HomeController@index', 'as'=>'admin.home']);
    Route::get('login', ['uses'=>'HomeController@signin', 'as'=>'admin.login']);
    Route::post('login', ['uses'=>'HomeController@doLogin', 'as'=>'admin.login']);
    Route::get('forgot-pass', ['uses'=>'HomeController@forgotPass', 'as'=>'admin.forgot_pass']);
    Route::post('forgot-pass', ['uses'=>'HomeController@sendPass', 'as'=>'admin.forgot_pass']);
    Route::get('dashboard', ['uses'=>'HomeController@dashboard', 'as' => 'admin.dashboard']);
    Route::get('logout', ['uses'=>'HomeController@logout', 'as' => 'admin.logout']);
    
    Route::post('users-data', ['uses'=>'HomeController@usersData', 'as'=>'admin.users-data']);
    Route::get('trips-data', ['uses'=>'HomeController@tripList', 'as'=>'admin.trips-data']);
    Route::get('users-list', ['uses'=>'HomeController@usersList', 'as'=>'admin.users-list']);
    Route::get('users-details/{user_id}', ['uses'=>'HomeController@usersDetails', 'as'=>'admin.users-details']);
    Route::get('add-category', ['uses'=>'HomeController@addCategory', 'as'=>'admin.add_category']);
    Route::post('add-category', ['uses'=>'HomeController@insertCategory', 'as'=>'admin.add_category']);
    Route::get('category-list', ['uses'=>'HomeController@categoryList', 'as'=>'admin.category-list']);
    Route::get('sub-category-list/{cat_id?}', ['uses'=>'HomeController@subCategoryLists', 'as'=>'admin.sub-category-list']);
    Route::get('sub-category-list', ['uses'=>'HomeController@subCategoryList', 'as'=>'admin.sub-category-list']);
    Route::get('edit-categories/{catID}', ['uses'=>'HomeController@updateCategory', 'as'=>'admin.edit_categories']);
    Route::get('edit-page', ['uses'=>'HomeController@EditPageCategory', 'as'=>'admin.edit_page']);
    Route::post('edit-categories', ['uses'=>'HomeController@updateCategorySubmit', 'as'=>'admin.update_categories']);
    Route::get('second-sub-category-list/{sub_cat_id}', ['uses'=>'HomeController@SecoundSubCategoryList', 'as'=>'admin.second-sub-category-list']);
    Route::get('user-list/{user_type}', ['uses'=>'HomeController@usersList', 'as'=>'admin.user-list']);
    Route::get('contact-list', ['uses'=>'HomeController@contactList', 'as'=>'admin.contact-list']);
    Route::get('advertise', ['uses'=>'HomeController@Advertise', 'as'=>'admin.advertise']);
    Route::post('change-img-link', ['uses'=>'HomeController@ChangeImageLink', 'as'=>'admin.change-img-link']);
    Route::get('change-language', ['uses'=>'HomeController@changeLanguage', 'as'=>'admin.change_language']);
    Route::get('update-lang-file', ['uses'=>'HomeController@updateLangaugeFile', 'as'=>'admin.update_lang_file']);
    Route::post('language-update-data', ['uses'=>'HomeController@languageUpdateData', 'as'=>'admin.language_update_data']);

resources/views/contact.blade.php
@extends('layouts/home')
{{-- Page title --}}
@section('title')
<!-- Write your page title here -->
@parent
@stop

{{-- page level styles --}}
@section('header_styles')
<!-- Write your css here -->
<style type='text/css'>
    .accprbtn button {
        background: #ffaf42;
        border-radius: 5px;
        color: #000;
        display: inline-block;
        font-family: "montserratregular";
        font-size: 18px;
        height: 49px;
        line-height: 49px;
        margin: 0;
        text-decoration: none;
        text-shadow: 1px 1px 1px #a0a0a0;
        width: 100%;
        text-align: center;
    }
    .has-error .form-control {
        border-color: #a94442 !important;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    }
</style>
@stop
{{-- Page content --}}
@section('content')
<!-- Start content -->
<div class="container">

    <div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s" data-wow-delay="0s">
        <div class="title-area">
            <h2 class="title">{{ trans('message.ContactUsHeading') }}</h2>
            <span class="line"></span>
        </div>
    </div>
    <div class="regfrm">
         @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if (session('flash_alert_notice'))
        <div class="flash-message">
            <div class="alert alert-{{session('flash_action')}}">
                <p>{{session('flash_alert_notice')}}</p>
            </div>
        </div>
        @endif

        <form action="{{route('user.contact')}}" method="POST" role="form" id="frm_contact">
            <div class="col-sm-12 col-md-7 col-lg-6 rgfrmin wow zoomIn" data-wow-duration="0.8s" data-wow-delay="0.5s">
                <div class="col-md-12 form-group">
                    <label>{{ trans('message.Name') }}</label>
                    <input type="text" class="form-control" placeholder="{{ trans('message.EnterYourName') }}" name="cname">
                </div>
                <div class="col-md-12 form-group">
                    <label>{{ trans('message.Email') }}</label>
                    <input type="text" class="form-control" placeholder="{{ trans('message.EnterYourEmailAddress') }}" name="cemail">
                </div>

                <div class="col-md-12 form-group">
                    <label>{{ trans('message.PhoneNo') }}</label>
                    <input type="text" class="form-control" placeholder="{{ trans('message.EnterYourPhoneNumber') }}" name="cphone">
                </div>

                <div class="col-md-12 form-group">
                    <label>{{ trans('message.MESSAGE') }}</label>
                    <textarea class="form-control" name="comment" placeholder="{{ trans('message.EnterYourMessage') }}"></textarea>
                </div>

                <div class="col-md-12 accprbtn">
                    <button>Submit</button>
                </div>
            </div><!-- End left panel -->
        </form>
    </div>
</div>
 
</div>
<!-- End content -->
@stop

@section('footer_scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $("#btn_profile_update").click(function() {
            $("#frm_profieupdate").submit();
        });
    });
    $('body').on('change', 'input[type="file"]', function(event) {
        var dd = $(this).parents('.uplsec').parent();
        var src = URL.createObjectURL(event.target.files[0]);
        dd.find('span').find('img').attr('src', src);
    });
</script>
<!-- Write your script here -->
@stop

resources/views/forgot.blade.php
@extends('layouts/login')
{{-- Page title --}}
@section('title')
<!-- Write your page title here -->
@parent
@stop

{{-- page level styles --}}
@section('header_styles')
<!-- Write your css here -->
@stop

{{-- Page content --}}
@section('content')

<div class="col-lg-5 col-md-6 col-sm-8 col-xs-12 sgin wow zoomIn" data-wow-duration="1.0s" data-wow-delay="1.0s">
    <div class="row">        
        <form action="{{route('user.forgotpassword')}}" method="POST" role="form" id="frm_forgotpass">                        
            <h5>Forgot Password</h5>
            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            @if (session('flash_alert_notice'))
            <div class="flash-message">
                <div class="alert alert-{{session('flash_action')}}">
                    <p>{{session('flash_alert_notice')}}</p>
                </div>
            </div>
            @endif
            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
            <div class="col-xs-12 form-group {{ $errors->first('email', 'has-error')}}">
                <span><img src="{{ asset('public/images/user.png') }}" alt=""/></span>
                <input class="form-control" placeholder="Enter Your Registered Mail ID" id="email" name="email" type="text">
            </div>            
            <div class="col-xs-12 form-group">
                <button type='submit' class="btn btn-primary btn-lg btn-block sgupbtn" id="btn_login" name="btn_login">Submit</a>
            </div>
            <a class="frgtpswd" href="{{route('user.signin')}}">Login</a>
            <p class="col-xs-12 lgnsup">New Member? <a href="{{route('user.signup')}}">Sign Up Now</a></p>
        </form>
    </div>
</div><!-- End Services -->
@stop

@section('footer_scripts')
<!-- Write your script here -->
<script type="text/javascript">
    $(document).ready(function() {
//        $("#btn_login").click(function() {
//            $("#frm_login").submit();
//        });
    });
</script>
@stop

resources/views/myprofile.blade.php
@extends('layouts/home')
{{-- Page title --}}
@section('title')
<!-- Write your page title here -->
@parent
@stop

{{-- page level styles --}}
@section('header_styles')
<!-- Write your css here -->
<style type='text/css'>
    .accprbtn button {background: #ffaf42;border-radius: 5px;color: #000;display: inline-block;font-family: "montserratregular";font-size: 18px;height: 49px;line-height: 49px;margin: 0;text-decoration: none;text-shadow: 1px 1px 1px #a0a0a0;width: 100%;text-align: center;}
    .has-error .form-control {border-color: #a94442 !important;-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);box-shadow: inset 0 1px 1px rgba(0,0,0,.075);}
</style>
@stop
{{-- Page content --}}
@section('content')
<!-- Start content -->
<div class="container">
    <div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s" data-wow-delay="0s">
        <div class="title-area">
            <h2 class="title">{{ trans('message.MyProfile') }}</h2>
            <span class="line"></span>
        </div>
    </div>
    
    <div class="col-md-12 byfrmot">        
        @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if (session('flash_alert_notice'))
        <div class="flash-message">
            <div class="alert alert-{{session('flash_action')}}">
                <p>{{session('flash_alert_notice')}}</p>
            </div>
        </div>
        @endif
        <form action="{{route('user.profile')}}" method="POST" role="form" id="frm_profieupdate" enctype="multipart/form-data">
            <input type="hidden" name="_token" value="{{ csrf_token() }}" />
            <div class="col-md-4 lftbar wow slideInLeft" data-wow-duration="0.8s" data-wow-delay="0.5s">
                <div class="col-xs-12 text-center">
                    <div class="uplsec">
                        @if(!empty($userinfo['userimage']))
                        <?php $path = route('home') . "/public/uploads/users/" . $userinfo['userimage']; ?>
                        <span><img width="135px" height="135px"  src="{{ $path}}" alt=""/></span>
                        @else
                        <span><img width="135px" height="135px" src="{{ asset('public/images/usrimg.png') }}" alt=""/></span>
                        @endif

                        <div class="uplbtnmn">
                            <div class="uplbtn">
                                <input type="file" value="" id="userimage" name="userimage"/>
                                <img src="{{ asset('public/images/uplbtn1.png') }}" alt=""/>
                            </div>
                        </div>
                    </div>	
                </div><!--upload image-->
                <div class="col-xs-12 form-group {{ $errors->first('username', 'has-error')}}">
                    <label>{{ trans('message.UserName') }}</label>
                    <input type="text" class="form-control" id='username' name='username' placeholder="{{ trans('message.EnterUserName') }}" value='{{(!empty($userinfo['username']))?$userinfo['username']:Input::old('username')}}'>
                </div>
                <p class="col-xs-12">{{ trans('message.permisssionContent') }}</p>
                <div class="col-xs-12 form-group {{ $errors->first('phone', 'has-error')}}">
                    <label>{{ trans('message.Phone') }}</label>
                    <input type="text" class="form-control" id='phone' name='phone' placeholder="{{ trans('message.EnterYourPhoneNumber') }}" value='{{(!empty($userinfo['phone']))?$userinfo['phone']:Input::old('phone')}}'>
                </div>
                <div class="col-xs-12 form-group {{ $errors->first('postalcode', 'has-error')}}">
                    <label>{{ trans('message.PostalCode') }}</label>
                    <input type="text" class="form-control" id='postalcode' name='postalcode' placeholder="{{ trans('message.PostalCode') }}" value='{{(!empty($userinfo['postalcode']))?$userinfo['postalcode']:Input::old('postalcode')}}'>
                </div>
                <div class="col-xs-12 form-group {{ $errors->first('city', 'has-error')}}">
                    <label>{{ trans('message.City') }}</label>
                    <input type="text" class="form-control" id='city' name='city'  placeholder="{{ trans('message.City') }}" value='{{(!empty($userinfo['city']))?$userinfo['city']:Input::old('city')}}'>
                </div>
                <div class="col-xs-12 form-group {{ $errors->first('country', 'has-error')}}">
                    <label>{{ trans('message.Country') }}</label>
                    <div class="ctyslct">
                        <select class="form-control" id='country' name='country'  >
                            @if(!empty($countries))
                            <option selected="" value=''>{{ trans('message.PleaseSelect') }}</option>
                            @foreach($countries as $key=>$objCountry)                           
                            @if(@Input::old('country') == @$key || @$userinfo['country'] == @$key)
                            <option value='{{$key}}' selected='selected'>{{$objCountry}}</option>
                            @else
                            <option value='{{$key}}'>{{$objCountry}}</option>
                            @endif
                            @endforeach
                            @endif                            
                        </select>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="col-xs-8 padd-left form-group {{ $errors->first('street', 'has-error')}}">
                        <label>{{ trans('message.Street') }}</label>
                        <input type="text" name='street' id='street' class="form-control" placeholder="{{ trans('message.EnterStreet') }}" value='{{(!empty($userinfo['street']))?$userinfo['street']:Input::old('street')}}'>
                    </div>	
                    <div class="col-xs-4 padd form-group {{ $errors->first('housenumber', 'has-error')}}">
                        <label>{{ trans('message.No') }}</label>
                        <input type="text" class="form-control" id='housenumber' name='housenumber' placeholder="{{ trans('message.HouseNumber') }}" value='{{(!empty($userinfo['housenumber']))?$userinfo['housenumber']:Input::old('housenumber')}}'>
                    </div>
                </div>               
            </div><!-- End left panel -->
        </form>    
        <div class="col-md-8 col-sm-12 rgtbarnw wow slideInRight" data-wow-duration="0.8s" data-wow-delay="0.5s">
            <div class="row">
                <h5>{{ trans('message.ListOfItems') }}</h5>
                <div class="table-responsive text-center bypftbl">
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>{{ trans('message.LOCATION') }}</th>
                                <th>{{ trans('message.DESTINATION') }}</th>
                                <th>{{ trans('message.OFFER') }}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="tableinhdtp">
                                <td width="10%"></td>
                                <td width="35%">
                                    <table class="tableinhd">
                                        <thead>
                                            <tr>
                                                <th style='width:33%;text-align:center;'>{{ trans('message.City') }}</th>
                                                <th style='width:33%;text-align:center;'>{{ trans('message.PostalCode') }}</th>
                                                <th style='width:33%;text-align:center;'>{{ trans('message.Country') }}</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </td>
                                <td width="35%">
                                    <table class="tableinhd">
                                        <thead>
                                            <tr>
                                                <th style='width:33%;text-align:center;'>{{ trans('message.City') }}</th>
                                                <th style='width:33%;text-align:center;'>{{ trans('message.PostalCode') }}</th>
                                                <th style='width:33%;text-align:center;'>{{ trans('message.Country') }}</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </td>
                                <td width="10%"></td>
                                <td width="10%"></td>
                            </tr>                            
                            @if(!empty($useritems))
                            @foreach($useritems as $objUserItems)
                            <tr>
                                <td class="itmimgtd">
                                        <?php $profile_pic = isset($objUserItems['item_image1']) && !empty($objUserItems['item_image1']) ? $objUserItems['item_image1'] : 'itmimg.png'; ?>
                                        <a href="{{ route('user.item-view',$objUserItems['id']) }}"> <span class="itmimg"><img class="driv_prof" src="{{ route('home'). "/public/uploads/items/" . $profile_pic }}" alt = ""/></span></a>
                                    </td>
                                <td>
                                    <table class="tblindata">
                                        <tbody>
                                            <tr>
                                                <td style='width:33%;text-align:center;'>{{$objUserItems['from_city']}}</td>
                                                <td style='width:33%;text-align:center;'>{{$objUserItems['from_postal_code']}}</td>
                                                <td style='width:33%;text-align:center;'>{{$countries[$objUserItems['from_country']]}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td>
                                    <table class="tblindata">
                                        <tbody>
                                            <tr>
                                                <td style='width:33%;text-align:center;'>{{$objUserItems['to_city']}}</td>
                                                <td style='width:33%;text-align:center;'>{{$objUserItems['to_postal_code']}}</td>
                                                <td style='width:33%;text-align:center;'>{{$countries[$objUserItems['to_country']]}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td>$ {{$objUserItems['item_price']}}</td>
                                <td class="acticns">
                                    <a href="{{route('item.edit', $objUserItems['id'])}}"><img src="{{ asset('public/images/edticn.png')}}" alt=""></a>
                                    <a href="{{route('item_destroy', $objUserItems['id'])}}"><img src="{{ asset('public/images/dlet.png')}}" alt=""></a>
                                </td>
                            </tr>
                            @endforeach
                            @else                            
                            <tr>
                                <td colspan="5">{{ trans('message.NoRecordAvailable') }} </td>
                            </tr>
                            @endif

                        </tbody>

                    </table>
                </div> 

                <div class="aditms">
                    <a class="additbtn" href="{{route('item.create')}}"><img src="{{ asset('public/images/plsicn.png') }}" alt=""/>{{ trans('message.AddNewItem') }} </a>
                    <div class="col-xs-12 form-group">
                        <label>{{ trans('message.NotDriver') }}</label>
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 askbtn">
                                <a href="{{route('user.driver_registration')}}">{{ trans('message.BecomeaDriver') }}</a>
                            </div>
                            <div class="col-xs-12 col-sm-6 accprbtn">
                                <a href="javascript:void(0)" id="btn_profile_update">{{ trans('message.Update') }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- End row -->
        </div><!-- End right panel -->
    </div>



</div>
<!-- End content -->
@stop

@section('footer_scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $("#btn_profile_update").click(function() {
            $("#frm_profieupdate").submit();
        });
    });
    $('body').on('change', 'input[type="file"]', function(event) {
        var dd = $(this).parents('.uplsec').parent();
        var src = URL.createObjectURL(event.target.files[0]);
        dd.find('span').find('img').attr('src', src);
    });
</script>
<!-- Write your script here -->
@stop